name: saltstack-proftpd-formula
source: https://github.com/bechtoldt/saltstack-proftpd-formula
summary: SaltStack Formula to set up and configure ProFTPD, a highly configurable FTP server
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
